// Phase 2: per-bot model selection.
//
// MODEL_NAME is the deployment default. Once a chat has named bots (Phase 3),
// each bot may carry its own tier in bots.model_tier and the reply must be
// generated by THAT model. The resolution is kept as a pure function so it can
// be tested without a live endpoint - the wiring that consumes it is exercised
// end-to-end by e2e-webhook.test.js once routing exists.

import test from "node:test";
import assert from "node:assert/strict";
import { readFile } from "node:fs/promises";
import path from "node:path";
import { fileURLToPath } from "node:url";

import { resolveModel, modelForBot, defaultModel } from "../model-config.js";

const ROOT = path.join(path.dirname(fileURLToPath(import.meta.url)), "..");

test("a bot's own tier wins over the deployment default", () => {
  assert.equal(
    resolveModel("nvidia/nemotron-3-ultra-550b-a55b:free", "default-model"),
    "nvidia/nemotron-3-ultra-550b-a55b:free"
  );
});

test("a missing or empty tier falls back to the default, so every existing bot keeps working", () => {
  assert.equal(resolveModel(null, "default-model"), "default-model");
  assert.equal(resolveModel(undefined, "default-model"), "default-model");
  assert.equal(resolveModel("", "default-model"), "default-model");
  assert.equal(resolveModel("   ", "default-model"), "default-model");
  assert.equal(resolveModel(42, "default-model"), "default-model", "a non-string tier must not be used verbatim");
});

test("a tier is trimmed, because a stray newline in a model id fails the request", () => {
  assert.equal(resolveModel("  vendor/model:free\n", "default-model"), "vendor/model:free");
});

test("modelForBot reads the tier off a bots row", () => {
  assert.equal(modelForBot({ model_tier: "tier-x" }, "d"), "tier-x");
  assert.equal(modelForBot({ model_tier: null }, "d"), "d");
  assert.equal(modelForBot(null, "d"), "d", "a missing row must not throw");
  assert.equal(modelForBot(undefined, "d"), "d");
});

test("with no fallback the deployment default is used, and it is read lazily", () => {
  const original = process.env.MODEL_NAME;
  try {
    process.env.MODEL_NAME = "env-default";
    assert.equal(defaultModel(), "env-default");
    assert.equal(resolveModel(null), "env-default");
    // Read at call time, not import time: db.js taught us that import-time env
    // reads depend on import order and fail confusingly.
    process.env.MODEL_NAME = "env-default-2";
    assert.equal(defaultModel(), "env-default-2");
  } finally {
    if (original === undefined) delete process.env.MODEL_NAME;
    else process.env.MODEL_NAME = original;
  }
});

// The seam only earns its keep if the reply path actually routes through it.
// Without this, resolveModel could be perfect and unused.
test("the reply path takes a model rather than hardcoding the global", async () => {
  const src = await readFile(path.join(ROOT, "server.js"), "utf8");

  assert.match(
    src,
    /async function callModelWithTools\(chatId, systemPrompt, userPrompt, model = MODEL_NAME\)/,
    "callModelWithTools must accept the model to use"
  );
  assert.match(
    src,
    /async function humanize\(chatId, text, model = MODEL_NAME\)/,
    "the humanizer must be able to use the same model as the reply"
  );
  assert.match(
    src,
    /async function sendBobReply\(chatId, senderId, userPrompt, tagUnsolicited, finalize, model = MODEL_NAME\)/,
    "sendBobReply must thread a model through"
  );

  // callModelWithTools must use the passed model, not the constant. Asserting
  // "no MODEL_NAME inside the body" is stronger than checking for the shape of
  // the call: it fails on any future hop that reaches for the global.
  const body = src.slice(src.indexOf("async function callModelWithTools("));
  // Skip the signature line: the default value there is allowed to be the
  // global, that is what "default" means. The BODY must not reach for it.
  const fn = body.slice(body.indexOf("\n") + 1, body.indexOf("\n}\n"));
  assert.ok(
    !fn.includes("MODEL_NAME"),
    "the tool loop body must not reference the MODEL_NAME constant"
  );
  assert.ok(
    (fn.match(/^\s*model,$/gm) ?? []).length >= 2,
    "each request in the tool loop must pass the model parameter"
  );
});
