// Phase 7: HTML document export.
//
// A group message can be exported as a document and delivered by Telegram, so
// no public host is needed. HTML first, deliberately: it has no dependency,
// it is readable on a phone, and it is useful on its own. PDF would need a
// headless browser or weasyprint and is only worth adding once someone asks.
//
// Everything user-supplied is escaped. A reply containing "</html>" or a
// <script> tag must not be able to alter the document.

export const MAX_TITLE = 120;

export function escapeDocHtml(str) {
  return String(str)
    .replace(/&/g, "&amp;")
    .replace(/</g, "&lt;")
    .replace(/>/g, "&gt;")
    .replace(/"/g, "&quot;")
    .replace(/'/g, "&#39;");
}

// A filesystem-safe name Telegram will accept, with an extension so a phone
// knows what it is. Unsafe characters are collapsed rather than stripped, so
// two different titles do not silently become the same file.
export function safeFileName(title, ext = "html") {
  const base = String(title ?? "")
    .trim()
    .replace(/[\\/:*?"<>|\u0000-\u001f]/g, "")
    .replace(/\s+/g, "-")
    .replace(/-+/g, "-")
    .replace(/^[.-]+|[.-]+$/g, "")
    .slice(0, 60);
  return `${base || "bob-document"}.${ext}`;
}

/**
 * Renders a document. The body is the model's raw reply text, escaped here -
 * it is NOT trusted HTML, so it is wrapped in <pre> and shown verbatim rather
 * than interpreted.
 *
 * @param {object} input
 * @param {string} input.title
 * @param {string} input.body      raw text (markdown is NOT interpreted)
 * @param {string} [input.source]  where it came from, e.g. a chat title
 * @param {string} [input.createdAt] ISO string
 * @returns {string} a complete HTML document
 */
export function renderDocumentHtml({ title, body, source, createdAt }) {
  const safeTitle = escapeDocHtml(String(title ?? "Bob document").slice(0, MAX_TITLE));
  const safeSource = source ? escapeDocHtml(source) : "";
  const safeBody = escapeDocHtml(body ?? "");
  const when = escapeDocHtml(createdAt ?? new Date().toISOString());

  return `<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<title>${safeTitle}</title>
<style>
  :root { color-scheme: light dark; }
  body { margin: 0 auto; max-width: 44rem; padding: 2rem 1.25rem;
         font: 16px/1.6 -apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, sans-serif; }
  header { border-bottom: 1px solid currentColor; padding-bottom: .75rem; margin-bottom: 1.25rem; }
  h1 { font-size: 1.5rem; margin: 0 0 .35rem; }
  .meta { font-size: .8rem; opacity: .7; }
  pre { white-space: pre-wrap; word-wrap: break-word; margin: 0;
        font: inherit; }
  footer { margin-top: 2rem; font-size: .75rem; opacity: .6; }
</style>
</head>
<body>
<header>
  <h1>${safeTitle}</h1>
  <div class="meta">${safeSource ? `${safeSource} &middot; ` : ""}${when}</div>
</header>
<pre>${safeBody}</pre>
<footer>Generated by Bob.</footer>
</body>
</html>
`;
}
