// Export formats.
//
// A format is a descriptor, not a branch in a handler: word, excel and zip are
// the documented next step, and each should be one entry here rather than a new
// if-chain. The handler dispatches through the registry.
//
// Pure renderers (text, markdown, csv, html) run in-process. PDF shells out to
// pdf_export.py, because the only HTML-to-PDF option that works on every target
// without a system dependency is ReportLab, which is Python.

import { renderDocumentHtml, safeFileName } from "./document.js";

// Pulls pipe-delimited tables out of model output. Telegram renders these as
// monospaced blocks; CSV and PDF need them as structure.
export function parseTables(body) {
  const lines = String(body ?? "").split("\n");
  const tables = [];
  let current = null;

  const isSeparator = (l) =>
    /\|/.test(l) && l.split("|").every((c) => c.trim() === "" || /^:?-+:?$/.test(c.trim()));
  const cells = (l) => {
    let t = l.trim();
    if (t.startsWith("|")) t = t.slice(1);
    if (t.endsWith("|")) t = t.slice(0, -1);
    return t.split("|").map((c) => c.trim());
  };

  for (let i = 0; i < lines.length; i++) {
    const line = lines[i];
    if (!line.includes("|")) {
      if (current && current.rows.length) tables.push(current);
      current = null;
      continue;
    }
    if (isSeparator(line)) {
      // A separator only means anything directly under a header row.
      if (current && current.headers.length && !current.rows.length) continue;
      continue;
    }
    if (!current) current = { headers: cells(line), rows: [] };
    else current.rows.push(cells(line));
  }
  if (current && current.rows.length) tables.push(current);
  // A header with no rows is not a table.
  return tables.filter((t) => t.rows.length > 0);
}

export function renderText(body) {
  return String(body ?? "");
}

export function renderMarkdown({ title, body } = {}) {
  const heading = title ? `# ${title}\n\n` : "";
  return `${heading}${String(body ?? "")}\n`;
}

// RFC 4180: a field containing a comma, a quote or a newline is wrapped in
// quotes, and an embedded quote is doubled.
function csvField(value) {
  const s = String(value ?? "");
  if (/[",\n\r]/.test(s)) return `"${s.replace(/"/g, '""')}"`;
  return s;
}

export function renderCsv(body) {
  const tables = parseTables(body);
  if (!tables.length) {
    // Prose exported as CSV must still contain the prose, not an empty file.
    return String(body ?? "")
      .split("\n")
      .map((line) => csvField(line))
      .join("\n");
  }
  const blocks = tables.map((t) => {
    const rows = [t.headers, ...t.rows];
    return rows.map((r) => r.map(csvField).join(",")).join("\n");
  });
  return `${blocks.join("\n\n")}\n`;
}

// PDF is generated by pdf_export.py. The contract is JSON in, a PDF file out,
// so the renderer is only a thin declaration here.
function renderPdf() {
  throw new Error("renderPdf is not called directly - see pdf_export.py");
}

export const EXPORT_FORMATS = [
  {
    id: "pdf",
    label: "PDF",
    extension: "pdf",
    mime: "application/pdf",
    needsProcess: true,
    render: renderPdf,
  },
  {
    id: "html",
    label: "HTML",
    extension: "html",
    mime: "text/html",
    render: ({ title, body, source }) => renderDocumentHtml({ title, body, source }),
  },
  {
    id: "markdown",
    label: "Markdown",
    extension: "md",
    mime: "text/markdown",
    render: renderMarkdown,
  },
  {
    id: "text",
    label: "Text",
    extension: "txt",
    mime: "text/plain",
    render: renderText,
  },
  {
    id: "csv",
    label: "CSV",
    extension: "csv",
    mime: "text/csv",
    render: renderCsv,
  },
];

export function listFormats() {
  return EXPORT_FORMATS;
}

export function getFormat(id) {
  return EXPORT_FORMATS.find((f) => f.id === id) ?? null;
}

// PDF, because a phone opens it without an extra app and it preserves layout.
export function defaultFormat() {
  return "pdf";
}

export function fileNameFor(format, title) {
  return safeFileName(title, format.extension);
}
