// What Bob remembers, and what it refuses to.
//
// WHY THIS EXISTS
//
// Bob is meant to be a colleague and a friend, not a search box. Told "my
// partner Sam is vegetarian and I'm allergic to peanuts", then asked "what
// should we order for dinner?", it must use that. Messages already persist, but
// nothing extracted FACTS from them - `users` held a name and a rolling
// summary, and a summary is regenerated by a model call that can drop or blur
// any of it.
//
// DELIBERATELY NOT A MODEL CALL
//
// Extracting facts with a model is the obvious design and the wrong one here.
// Roughly half of all calls to the free tier fail (measured), so every
// inference-heavy feature is also a reliability feature. A missed memory is a
// far smaller failure than a failed reply, and the patterns below are the
// high-signal ones: they cover who someone is, what they need, and what they
// must never be exposed to.
//
// The trade-off is honest: a fact phrased unusually will be missed. That is
// preferable to a system that spends its reliability budget on classification.

// "my partner is vegetarian", "I'm allergic to X", "call me Sam".
const FIRST_PERSON_RE =
  /\b(?:i'?m|i am|i'?ve got|i have|my)\b[^.\n!?]{0,60}\b(allergic|vegetarian|vegan|coeliac|celiac|nut allergy|lactose|diabet\w*|pregnant|on medication|deadline|due|working (?:from|at|on)|based in|living in|moving to|my (?:partner|wife|husband|manager|boss|dog|cat|team|company|birthday))\b/i;

// Third parties the user names: "my partner Sam", "my manager Priya".
const THIRD_PARTY_RE =
  /\bmy\s+(partner|wife|husband|girlfriend|boyfriend|manager|boss|colleague|teammate|team|son|daughter|dog|cat|mum|mom|dad|father|mother|brother|sister)\s+([A-Z][a-z]+)/;

// Corrections: "actually Sam eats meat", "no longer allergic".
const CORRECTION_RE = /\b(?:actually|correction|i meant|no longer|not any more|these days|now)\b/i;

// Things that must never be stored: credentials, health records beyond the
// volunteered fact, third-party private details. Kept explicit so the
// exclusions are auditable rather than implied.
const NEVER_STORE_RE =
  /\b(?:password|passcode|api[_ -]?key|token|secret|credit card|card number|ssn|social security|bank account|routing number)\b/i;

const MAX_FACT_LEN = 200;

/** A statement of fact about the user or someone they named. */
export function extractFacts(text) {
  if (typeof text !== "string") return [];
  const raw = String(text);
  if (!raw.trim() || NEVER_STORE_RE.test(raw)) return [];

  const facts = [];

  // Third parties first: "my partner Sam is vegetarian" yields the fact about
  // Sam, which is the part needed later.
  for (const m of raw.matchAll(new RegExp(THIRD_PARTY_RE.source, "gi"))) {
    const relation = m[1].toLowerCase();
    const name = m[2];
    const rest = raw.slice(m.index + m[0].length);
    const attr = rest.match(
      /\b(is|are|works as|lives in|likes|love|prefers|allergic to|vegetarian|vegan)\b([^.\n!?]{0,40})/i
    );
    const detail = attr ? ` ${attr[1].toLowerCase()} ${attr[2].trim()}` : "";
    facts.push(`${name} (my ${relation})${detail}`.trim().slice(0, MAX_FACT_LEN));
  }

  if (FIRST_PERSON_RE.test(raw)) {
    // Store the whole sentence: trimming it to the matched fragment loses the
    // subject, and "allergic to peanuts" without "I'm" is ambiguous.
    const sentence = raw.split(/[.!?\n]/).find((s) => FIRST_PERSON_RE.test(s)) ?? raw;
    facts.push(sentence.trim().slice(0, MAX_FACT_LEN));
  }

  return [...new Set(facts.filter(Boolean))].slice(0, 3);
}

/** Detects a correction, so a stale fact can be retracted. */
export function looksLikeCorrection(text) {
  return typeof text === "string" && CORRECTION_RE.test(text);
}

/** Renders facts for the prompt. Stable ordering keeps the cache prefix put. */
export function formatFacts(facts) {
  if (!Array.isArray(facts) || facts.length === 0) return "";
  return facts.map((f) => `- ${f}`).join("\n");
}